"""initial schema

Revision ID: 76f00d0e35cb
Revises: 
Create Date: 2026-10-06 16:40:37.715601
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '76f00d0e35cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('previous_state', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_creatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('account_name', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('ecosystem_code', sa.String(length=80), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=True),
    sa.Column('holdout', sa.Boolean(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('metrics_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ecosystems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('model_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('capability', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=True),
    sa.Column('model_version', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'capability')
    )
    op.create_table('policy_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('scope_level', sa.String(length=40), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('rule_kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'content_hash', 'scope_level', 'scope_id')
    )
    op.create_table('programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('regression_tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('expected_decision', sa.Text(), nullable=False),
    sa.Column('pass_conditions', sa.JSON(), nullable=False),
    sa.Column('fail_conditions', sa.JSON(), nullable=False),
    sa.Column('source_rule', sa.Text(), nullable=False),
    sa.Column('evaluation_mode', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('skill_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('source_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_table('validation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'slug')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('capability', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_refs', sa.JSON(), nullable=False),
    sa.Column('output_refs', sa.JSON(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_ecosystems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('ecosystem_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'ecosystem_id')
    )
    op.create_table('reference_banks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('ecosystem_id', sa.String(length=36), nullable=True),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_path')
    )
    op.create_table('skill_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('scope_level', sa.String(length=40), nullable=False),
    sa.Column('rule_kind', sa.String(length=40), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_version_id', sa.String(length=36), nullable=True),
    sa.Column('approval_state', sa.String(length=40), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'content_hash')
    )
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('check_code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_dna_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_profile_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'version_number')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'slug')
    )
    op.create_table('account_dna_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('evidence_kind', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.String(length=40), nullable=True),
    sa.Column('date_end', sa.String(length=40), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['account_dna_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('ecosystem_id', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('holdout', sa.Boolean(), nullable=False),
    sa.Column('current_approved_story_lock_version_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'slug')
    )
    op.create_table('creative_genomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('creative_id', sa.String(length=36), nullable=True),
    sa.Column('variable_dimension', sa.String(length=80), nullable=False),
    sa.Column('fixed_notes', sa.Text(), nullable=True),
    sa.Column('primary_metric', sa.String(length=80), nullable=True),
    sa.Column('secondary_metrics', sa.JSON(), nullable=False),
    sa.Column('measurement_window', sa.String(length=120), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=40), nullable=True),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mechanic_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('dimension', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_locks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_id')
    )
    op.create_table('comment_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('example_comments', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('unexpected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('stance', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('fixed', sa.JSON(), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genome_facets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('genome_id', sa.String(length=36), nullable=False),
    sa.Column('dimension', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('assignment', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['genome_id'], ['creative_genomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('post_age_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('measurement_window', sa.String(length=120), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('profile_visits', sa.Integer(), nullable=True),
    sa.Column('link_clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.String(length=40), nullable=True),
    sa.Column('watch_notes', sa.Text(), nullable=True),
    sa.Column('slide_notes', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_lock_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_lock_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_version_id', sa.String(length=36), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_lock_id'], ['story_locks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_lock_id', 'version_number')
    )
    with op.batch_alter_table('creatives') as batch_op:
        batch_op.create_foreign_key(
            'fk_creative_current_lock',
            'story_lock_versions',
            ['current_approved_story_lock_version_id'],
            ['id'],
        )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=True),
    sa.Column('reference_bank_id', sa.String(length=36), nullable=True),
    sa.Column('bound_story_lock_version_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('rights_status', sa.String(length=40), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('present_in_snapshot', sa.Boolean(), nullable=False),
    sa.Column('source_exists_claim', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('ecosystem_code', sa.String(length=80), nullable=True),
    sa.Column('story_key', sa.String(length=160), nullable=True),
    sa.Column('editing_method', sa.String(length=120), nullable=True),
    sa.Column('provider_name', sa.String(length=120), nullable=True),
    sa.Column('model_version', sa.String(length=120), nullable=True),
    sa.Column('product_model', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bound_story_lock_version_id'], ['story_lock_versions.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['reference_bank_id'], ['reference_banks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_path')
    )
    op.create_table('comment_doors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('story_lock_version_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('prediction_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['story_lock_version_id'], ['story_lock_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('continuity_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_lock_version_id', sa.String(length=36), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['story_lock_version_id'], ['story_lock_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slide_projections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_lock_version_id', sa.String(length=36), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('beat', sa.Text(), nullable=True),
    sa.Column('relative_time', sa.Text(), nullable=True),
    sa.Column('visible_clock', sa.Text(), nullable=True),
    sa.Column('visible_date', sa.Text(), nullable=True),
    sa.Column('overlay', sa.Text(), nullable=True),
    sa.Column('order_state', sa.Text(), nullable=True),
    sa.Column('actor_knowledge', sa.Text(), nullable=True),
    sa.Column('actor_location', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['story_lock_version_id'], ['story_lock_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_lock_version_id', 'slide_index')
    )
    op.create_table('story_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_lock_version_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('quantity', sa.String(length=40), nullable=True),
    sa.Column('unit_price', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('generation', sa.String(length=40), nullable=True),
    sa.Column('variant', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('pack_count', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['story_lock_version_id'], ['story_lock_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_lock_version_id', 'position')
    )
    op.create_table('viral_texture_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_lock_version_id', sa.String(length=36), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['story_lock_version_id'], ['story_lock_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('related_asset_id', sa.String(length=36), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['related_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'related_asset_id', 'relation')
    )
    op.create_table('comment_door_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('door_id', sa.String(length=36), nullable=True),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('relationship', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['comment_clusters.id'], ),
    sa.ForeignKeyConstraint(['door_id'], ['comment_doors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stale_artifact_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('story_lock_version_id', sa.String(length=36), nullable=True),
    sa.Column('superseded_by_version_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['story_lock_version_id'], ['story_lock_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creatives') as batch_op:
        batch_op.drop_constraint('fk_creative_current_lock', type_='foreignkey')
    op.drop_table('stale_artifact_records')
    op.drop_table('comment_door_mappings')
    op.drop_table('asset_relations')
    op.drop_table('viral_texture_details')
    op.drop_table('story_line_items')
    op.drop_table('slide_projections')
    op.drop_table('continuity_entries')
    op.drop_table('comment_doors')
    op.drop_table('assets')
    op.drop_table('story_lock_versions')
    op.drop_table('performance_snapshots')
    op.drop_table('genome_facets')
    op.drop_table('experiment_variants')
    op.drop_table('comments')
    op.drop_table('comment_clusters')
    op.drop_table('story_locks')
    op.drop_table('posts')
    op.drop_table('mechanic_observations')
    op.drop_table('experiments')
    op.drop_table('creative_genomes')
    op.drop_table('creatives')
    op.drop_table('account_dna_observations')
    op.drop_table('campaigns')
    op.drop_table('account_dna_profiles')
    op.drop_table('validation_results')
    op.drop_table('skill_versions')
    op.drop_table('reference_banks')
    op.drop_table('program_ecosystems')
    op.drop_table('model_runs')
    op.drop_table('accounts')
    op.drop_table('validation_runs')
    op.drop_table('source_artifacts')
    op.drop_table('skill_artifacts')
    op.drop_table('regression_tests')
    op.drop_table('programs')
    op.drop_table('policy_rules')
    op.drop_table('model_providers')
    op.drop_table('ecosystems')
    op.drop_table('benchmark_creatives')
    op.drop_table('approval_events')
    # ### end Alembic commands ###
