# Commercial-occupation diagnostic corpus — single source of truth.
# One row per DISTINCT commercial question (deduped INT/NT/BOUNDARY).
# OCCUPATION: UNOWNED | PARTIALLY OWNED | OWNED | UNCLEAR
# NARRATIVE RELATION: COMPETING | COMPLEMENTARY | IRRELEVANT | RESIDUAL | N/A
C = []
def add(**k):
    C.append(k)

TR = "TRANSCRIPT_RECOVERY"
OD = "ON_DISK"

# ============================================================
# RUN 4 — usable boundaries (disk stub; names from VS report / brief)
# ============================================================
add(
    run=4, id="R4-B1", types="BOUNDARY|RESEARCHED",
    world="Access-code / entry barrier (~$95 usable boundary)",
    gravity="MIXED",
    q="How do I cross an ~$95 access-code / entry barrier to participate?",
    q_indep="UNCLEAR",
    answers="Not recoverable from disk stub; Run4 researched 2 stacks in low-attention worlds (access code among named stacks).",
    owner="UNKNOWN (TRANSCRIPT_RECOVERY)",
    occ="UNCLEAR",
    rel="N/A",
    evidence="VS final report + Run5 comparison name 'access code' as Run4 stack world; RUN4_CORRECTED_V1.2.md is header-only stub.",
    stage="UNKNOWN",
    helped="UNCLEAR",
    how="added no information (record too thin to classify occupation honestly)",
    naive_fn="NO",
    prov=TR,
    note="no natural-question detail on disk — not inventing owner/occupation",
)
add(
    run=4, id="R4-B2", types="BOUNDARY|RESEARCHED",
    world="Used → preferred new car seat / infant seat",
    gravity="MIXED",
    q="How do I move from used/settling seat to preferred new seat?",
    q_indep="UNCLEAR",
    answers="Not recoverable; named as Run4 'infant seat' stack world.",
    owner="UNKNOWN (TRANSCRIPT_RECOVERY)",
    occ="UNCLEAR",
    rel="N/A",
    evidence="VS report usable-boundary list; Run5 comparison 'infant seat' stack; disk stub.",
    stage="UNKNOWN",
    helped="UNCLEAR",
    how="added no information (record too thin)",
    naive_fn="NO",
    prov=TR,
    note="TRANSCRIPT_RECOVERY — occupation not invented",
)
add(
    run=4, id="R4-B3", types="BOUNDARY",
    world="Roommate lockbox / fridge lunch security",
    gravity="YES",
    q="How do I secure lunch / stop fridge theft without social escalation?",
    q_indep="YES",
    answers="Ordinary lockbox purchase (trivial basket); social call-out. Run6 echoed as collapsed ordinary-utility.",
    owner="ORDINARY CHEAP SUBSTITUTES",
    occ="OWNED",
    rel="COMPETING",
    evidence="Brief usable list + Run6 collapsed 'Lockbox cheaper after lunch theft — trivial basket; same secure-lunch outcome'.",
    stage="POST-SCOUT / PRE-SYNTHESIS",
    helped="YES",
    how="prevented wasted synthesis (ordinary utility / same outcome)",
    naive_fn="NO",
    prov=TR,
    note="Cross-run echo from Run6 imaginary/collapsed reinforces ownership; still TRANSCRIPT_RECOVERY for Run4 detail",
)
add(
    run=4, id="R4-B4", types="BOUNDARY|RESEARCHED",
    world="Rx dog food ~$50 shortfall",
    gravity="MIXED",
    q="How do I complete / afford Rx diet dog food given ~$50 shortfall?",
    q_indep="UNCLEAR",
    answers="Not recoverable; named as Run4 'Rx diet' stack world; adjacent to Run5 inhaler existing-cause family.",
    owner="UNKNOWN (possible DISCOUNT CARDS / RETAILER by analogy — NOT used to classify)",
    occ="UNCLEAR",
    rel="N/A",
    evidence="VS report name only; Run5 inhaler GoodRx kill is adjacent world, deliberately not imported (anti-gaming).",
    stage="UNKNOWN",
    helped="UNCLEAR",
    how="added no information (thin record; refused analogy upgrade)",
    naive_fn="NO",
    prov=TR,
    note="anti-gaming: did not import Run5 GoodRx ownership into Run4 Rx-diet",
)
add(
    run=4, id="R4-B5", types="BOUNDARY",
    world="SelectTech shortfall (home weights)",
    gravity="MIXED",
    q="How do I cover a SelectTech / adjustable-weight shortfall to get preferred equipment?",
    q_indep="UNCLEAR",
    answers="Not recoverable from disk.",
    owner="UNKNOWN",
    occ="UNCLEAR",
    rel="N/A",
    evidence="Named only in VS/brief usable-boundary list.",
    stage="UNKNOWN",
    helped="UNCLEAR",
    how="added no information",
    naive_fn="NO",
    prov=TR,
    note="TRANSCRIPT_RECOVERY",
)

# Run 4 NT
add(
    run=4, id="R4-NT1", types="NT",
    world="Halloween costume already chosen",
    gravity="UNCLEAR",
    q="NONE",
    q_indep="UNCLEAR",
    answers="N/A — recovered line is purchaser-side 'already chosen' only.",
    owner="UNKNOWN",
    occ="UNCLEAR",
    rel="N/A",
    evidence="VS corpus R4-NT1 VS-X; no object/price/path on disk.",
    stage="UNKNOWN",
    helped="NO",
    how="added no information",
    naive_fn="NO",
    prov=TR,
    note="no natural economic question — not whitespace",
)
add(
    run=4, id="R4-NT2", types="NT",
    world="Family hosting via ordinary takeout",
    gravity="YES",
    q="How do I host family without cooking, at lower cost?",
    q_indep="YES",
    answers="Ordinary takeout / delivery already enables no-cook hosting.",
    owner="ORDINARY CHEAP SUBSTITUTES",
    occ="OWNED",
    rel="COMPETING",
    evidence="VS R4-NT2 VS-0; NT reason: ordinary takeout already enables outcome.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis (cheaper-same in home category)",
    naive_fn="NO",
    prov=TR,
)
add(
    run=4, id="R4-NT3", types="NT",
    world="Bowflex already being bought at sale",
    gravity="MIXED",
    q="How do I get Bowflex cheaper than the sale price I'm already paying?",
    q_indep="YES",
    answers="Retailer sale event already is the discount path.",
    owner="RETAILER SALES",
    occ="OWNED",
    rel="COMPETING",
    evidence="VS R4-NT3 VS-0.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=TR,
)
add(
    run=4, id="R4-NT4", types="NT",
    world="Byredo fragrance already chosen",
    gravity="UNCLEAR",
    q="NONE",
    q_indep="UNCLEAR",
    answers="N/A — already-chosen purchaser fact only; no dupe/price record for Run4.",
    owner="UNKNOWN",
    occ="UNCLEAR",
    rel="N/A",
    evidence="VS R4-NT4 VS-X; refused R5-NT3 analogy (anti-gaming).",
    stage="UNKNOWN",
    helped="NO",
    how="added no information",
    naive_fn="NO",
    prov=TR,
    note="no natural economic question recoverable — not whitespace; anti-gaming refused dupe upgrade",
)
add(
    run=4, id="R4-NT5", types="NT",
    world="Skincare haul regret",
    gravity="MIXED",
    q="NONE",
    q_indep="NO",
    answers="N/A — tension is product expectation vs reality, not a commercial access question.",
    owner="UNKNOWN",
    occ="UNCLEAR",
    rel="N/A",
    evidence="VS R4-NT5 VS-X.",
    stage="UNKNOWN",
    helped="NO",
    how="added no information",
    naive_fn="NO",
    prov=TR,
    note="no natural economic question — not whitespace",
)
add(
    run=4, id="R4-NT6", types="NT",
    world="Dishwasher already being repaired",
    gravity="MIXED",
    q="How do I keep appliance continuity cheaper than the repair path already chosen?",
    q_indep="YES",
    answers="Ordinary repair path already chosen.",
    owner="OTHER (ordinary repair path)",
    occ="OWNED",
    rel="COMPETING",
    evidence="VS R4-NT6 VS-0.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=TR,
)
add(
    run=4, id="R4-NT7", types="NT",
    world="Broken glasses → cheap online already closes delayed→now",
    gravity="YES",
    q="How do I replace broken glasses sooner without paying optometrist retail?",
    q_indep="YES",
    answers="Cheap online eyewear channel (named in NT reason).",
    owner="ORDINARY CHEAP SUBSTITUTES",
    occ="OWNED",
    rel="COMPETING",
    evidence="VS R4-NT7 VS-1; channel named in NT reason.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=TR,
)

# ============================================================
# RUN 5 — usable boundaries / INTs (deduped) + NTs
# ============================================================
add(
    run=5, id="R5-B1/INT-1", types="BOUNDARY|INT|FILTERED|RESEARCHED",
    world="UPPAbaby Kona → preferred Nuna Triv LX (stroller settling)",
    gravity="YES",
    q="How do I reach preferred Triv LX (~$950) instead of settling for Kona (~$650) given ~$300 gap?",
    q_indep="YES",
    answers="Registry discounts; open-box; choose TRVL LX (~$600) as travel substitute; multi-factor feature preference often binds more than price.",
    owner="RETAILER SALES; ORDINARY CHEAP SUBSTITUTES; OTHER (registry/open-box)",
    occ="PARTIALLY OWNED",
    rel="RESIDUAL",
    evidence="Run5 B1/INT-1/R1: gap real; registry/open-box/TRVL occupy parts of 'get preferred cheaper'; research found price often not binder → residual not campaign-usable.",
    stage="POST-SCOUT / PRE-SYNTHESIS",
    helped="YES",
    how="preserved residual space (correct PARTIALLY OWNED/RESIDUAL vs naive full OWNED kill) AND still would not have produced survivor — research needed for binder test",
    naive_fn="YES",
    prov=OD,
    note="FN test: naive 'deal/registry content = OWNED' would over-kill; honest tag is PARTIALLY OWNED/RESIDUAL; residual later failed evidence not occupation",
)
add(
    run=5, id="R5-B2/INT-2", types="BOUNDARY|INT|FILTERED",
    world="Home walking pad affordability",
    gravity="YES",
    q="How do I afford a walking pad (~$100–$214) to participate in home walking?",
    q_indep="YES",
    answers="Target/Amazon deep markdowns already common; strike-price sales already in market.",
    owner="RETAILER SALES; CLEARANCE/MARKDOWNS",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run5 B2/INT-2 filter FAIL: existing deep retail markdowns.",
    stage="POST-SCOUT / PRE-SYNTHESIS",
    helped="YES",
    how="prevented wasted synthesis (filter already failed; early occupation tag would have matched)",
    naive_fn="NO",
    prov=OD,
)
add(
    run=5, id="R5-B3/INT-3", types="BOUNDARY|INT|FILTERED|RESEARCHED",
    world="Inhaler cash-price spike (abandon → complete fill)",
    gravity="YES",
    q="How do I complete an inhaler fill when pharmacy quotes ~$156 cash instead of expected copay?",
    q_indep="YES",
    answers="GoodRx / manufacturer / pharmacy discount cards routinely undercut cash.",
    owner="DISCOUNT CARDS",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run5 B3 map HIGH existing-cause; R2 adversarial kill EVIDENCE+OWNERSHIP (GoodRx ~$78–$92).",
    stage="POST-SCOUT / PRE-SYNTHESIS",
    helped="YES",
    how="prevented wasted synthesis/research — map already HIGH; filter still PASSed; occupation OWNED at map stage could have filter-failed earlier",
    naive_fn="NO",
    prov=OD,
)
add(
    run=5, id="R5-B4/INT-4", types="BOUNDARY|INT|FILTERED",
    world="Teacher classroom essentials budget remainder",
    gravity="YES",
    q="How do I stretch ~$100 leftover / out-of-pocket to cover named classroom essentials?",
    q_indep="YES",
    answers="DonorsChoose, PTA, teacher stores; ordinary replenishment salience.",
    owner="OTHER (DonorsChoose/PTA); RETAILER SALES",
    occ="PARTIALLY OWNED",
    rel="COMPETING",
    evidence="Run5 B4/INT-4 filter FAIL: thin + ordinary replenishment + DonorsChoose existing.",
    stage="POST-SCOUT / PRE-SYNTHESIS",
    helped="YES",
    how="prevented wasted synthesis (filter already failed)",
    naive_fn="NO",
    prov=OD,
    note="Cultural gravity LOW-DG niche — PARTIALLY OWNED not useful whitespace",
)
add(
    run=5, id="R5-NT1", types="NT",
    world="Halloween décor cheaper",
    gravity="YES",
    q="How do I get seasonal Halloween décor for less?",
    q_indep="YES",
    answers="Seasonal retailer sales already.",
    owner="RETAILER SALES; RETAILER PROMO CALENDARS",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run5 NT1; HIGH DG G1; VS VS-0.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
)
add(
    run=5, id="R5-NT2", types="NT",
    world="Target fall haul cheaper",
    gravity="YES",
    q="How do I get the Target fall haul cheaper?",
    q_indep="YES",
    answers="Category already 'finds/deals'; Target deal surfaces + haul genre.",
    owner="AFFILIATE DEAL CONTENT; RETAILER SALES",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run5 NT2; VS VS-1.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
)
add(
    run=5, id="R5-NT3/INT-5", types="NT|INT",
    world="LV Imagination scent vs Montagne Imaginary dupe",
    gravity="YES",
    q="How do I obtain the Imagination scent outcome without paying ~$330 for the OG bottle?",
    q_indep="YES",
    answers="Montagne Imaginary ~$50 verified; OG-vs-dupe comparison culture.",
    owner="DUPES",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run5 NT3 + INT-5 rejected at synthesis → organic-only; VS VS-2.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis (NT/existing-cause already)",
    naive_fn="NO",
    prov=OD,
    note="Critical unit: question is scent access, not 'LV bottle cheaper'. Dupe owns scent question.",
)
add(
    run=5, id="R5-NT4", types="NT",
    world="KPop Demon Hunters licensed kids costume",
    gravity="YES",
    q="How do I obtain the licensed KPDH costume when it is sold out?",
    q_indep="YES",
    answers="Spirit/licensed retail restock; parent hunt networks. Promo cannot mint inventory. In-stock price ~$59.99.",
    owner="INVENTORY NETWORKS; RESTOCK/DROP NETWORKS",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run5 NT4; VS VS-1; inventory scarcity = observation not whitespace.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
    note="anti-gaming: inventory scarcity NOT upgraded to UNOWNED whitespace",
)
add(
    run=5, id="R5-NT5", types="NT",
    world="Labubu / Pop Mart blind box retail vs scalper",
    gravity="YES",
    q="How do I obtain Labubu at retail (~$18–$22) instead of scalper price?",
    q_indep="YES",
    answers="Pop Mart drop/restock ritual; official retail exists; hunt posts.",
    owner="RESTOCK/DROP NETWORKS; SCALPER/RESALE",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run5 NT5; VS VS-2; brief example of correct unit.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
    note="anti-gaming: affiliate/scalper talk ≠ automatic; restock ritual answers the specific question → OWNED",
)
add(
    run=5, id="R5-NT6", types="NT",
    world="Heated throw cheaper",
    gravity="MIXED",
    q="How do I get a heated throw cheaper?",
    q_indep="YES",
    answers="Ordinary retail pricing / seasonal sales ($30–$75 approx.).",
    owner="RETAILER SALES",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run5 NT6; VS VS-0; NOT upgraded via tutorial-pinned $5.99 heated blanket (anti-gaming).",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
    note="anti-gaming: historical winner knowledge not used to upgrade",
)
add(
    run=5, id="R5-NT7", types="NT",
    world="Dryer balls / scent boosters cheaper",
    gravity="NO",
    q="NONE",
    q_indep="NO",
    answers="N/A — trivial basket; same laundry outcome; no unresolved access question.",
    owner="ORDINARY CHEAP SUBSTITUTES",
    occ="UNCLEAR",
    rel="N/A",
    evidence="Run5 NT7; VS VS-0; DG NONE.",
    stage="SCOUT OUTPUT",
    helped="NO",
    how="added no information (no natural economic question — not whitespace)",
    naive_fn="NO",
    prov=OD,
    note="no natural economic question — not whitespace; FP guard: low-interest ≠ UNOWNED opportunity",
)
add(
    run=5, id="R5-NT8", types="NT",
    world="Concert ticket fees covered",
    gravity="YES",
    q="How do I avoid or cover ticketing fees that nearly equal face value?",
    q_indep="YES",
    answers="Same show either way; fee-outrage discourse owns the grievance; salience-reject shape.",
    owner="OTHER (ticketing fee-outrage discourse); STORE POLICY",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run5 NT8; VS VS-1.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
)

# ============================================================
# RUN 6 — boundaries/INTs deduped + NTs + LH-origin
# ============================================================
add(
    run=6, id="R6-B1/INT-1", types="BOUNDARY|INT|FILTERED|RESEARCHED",
    world="Home Depot 12-ft Skelly classic $299 → Ultra $379",
    gravity="YES",
    q="How do I get Ultra 12-ft interactive/talk features instead of settling for classic given $80 sticker gap?",
    q_indep="YES",
    answers="(1) Buy classic $299. (2) Buy 6.5-ft Ultra $279 (app/talk/record already). (3) HD restock alerts. (4) Resale worse. Boundary map already named restock + 6.5-ft substitute.",
    owner="RESTOCK/DROP NETWORKS; ORDINARY CHEAP SUBSTITUTES; RETAILER SALES",
    occ="OWNED",
    rel="COMPETING",
    evidence="SYNTHESIS_BOUNDARY_MAP B1 already-explains; ADVERSARIAL R1 OWNERSHIP+EVIDENCE; Gate2A/salience FAIL.",
    stage="POST-SCOUT / PRE-SYNTHESIS",
    helped="YES",
    how="prevented wasted synthesis/research — map already listed 6.5-ft + restock; filter still PASSed on 'residual uncertain'; early OWNED tag could have filter-failed",
    naive_fn="NO",
    prov=OD,
)
add(
    run=6, id="R6-B2/INT-2", types="BOUNDARY|INT|FILTERED",
    world="Full-size candy house vs settling minis",
    gravity="YES",
    q="How do I execute a full-size candy house instead of settling for minis on a neighborhood bag plan?",
    q_indep="YES",
    answers="Costco/club Halloween full-size deals already common (e.g. 30-ct ~$19.99 deal posts).",
    owner="RETAILER SALES; AFFILIATE DEAL CONTENT; CLEARANCE/MARKDOWNS",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run6 B2 HIGH existing-cause; INT-2 filter FAIL.",
    stage="POST-SCOUT / PRE-SYNTHESIS",
    helped="YES",
    how="prevented wasted synthesis (filter already failed; occupation matches)",
    naive_fn="NO",
    prov=OD,
)
add(
    run=6, id="R6-B3/INT-3", types="BOUNDARY|INT|FILTERED",
    world="Beauty advent calendar access (Sephora/Ulta-style)",
    gravity="MIXED",
    q="How do I obtain the preferred named beauty advent calendar despite sticker/resale/sellout friction?",
    q_indep="YES",
    answers="Alternate calendars in stock; early-buy; resale; sellout → inventory binder often dominates.",
    owner="INVENTORY NETWORKS; ORDINARY CHEAP SUBSTITUTES; SCALPER/RESALE",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run6 B3 map risks; INT-3 filter FAIL thin + inventory + ordinary gift-save.",
    stage="POST-SCOUT / PRE-SYNTHESIS",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
    note="Thin engines; cultural gravity weak — not useful whitespace even if partial price gap remains",
)
add(
    run=6, id="R6-NT1", types="NT",
    world="Classic Skelly cheaper (same silhouette)",
    gravity="YES",
    q="How do I get the classic 12-ft Skelly cheaper than HD $299?",
    q_indep="YES",
    answers="HD $299 is the access path when in stock; restock ritual.",
    owner="RETAILER SALES; RESTOCK/DROP NETWORKS",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run6 NT1; distinct question from classic→Ultra upgrade (R6-B1).",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
    note="Same object, different economic question from R6-B1 — kept as separate row",
)
add(
    run=6, id="R6-NT2", types="NT",
    world="Pottery Barn ghost mirror vs HomeGoods/Walmart dupes",
    gravity="YES",
    q="How do I get the PB ghost-mirror look without Pottery Barn price?",
    q_indep="YES",
    answers="HomeGoods/Walmart dupes; treasure-hunt culture (OC-03).",
    owner="DUPES",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run6 NT2; VS VS-2.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
)
add(
    run=6, id="R6-NT3/INT-4", types="NT|INT|LH-ORIGIN",
    world="Anti-blush look / MAC Film Noir Buff (LH Card 1)",
    gravity="YES",
    q="How do I achieve the anti-blush look / obtain Film Noir Buff when sold out or expensive?",
    q_indep="YES",
    answers="MUA already-own method (bronzer+lipstick); dupes; sellout = inventory. Origin creator seeking dupe.",
    owner="DUPES; KNOWN HACKS/METHODS",
    occ="OWNED",
    rel="COMPETING",
    evidence="LH Card 1; Run6 NT3; INT-4 organic-only; VS VS-2; appendix E owned.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis; LH alone surfaced heat — occupation explains why no commercial A→B",
    naive_fn="YES",
    prov=OD,
    note="FN/FP nuance: naive 'deal/affiliate content = OWNED' might MISS this (method/dupe own it without deal posts) and falsely call UNOWNED; honest OWNED via KNOWN HACKS/METHODS+DUPES. Cultural gravity YES.",
)
add(
    run=6, id="R6-NT4", types="NT|LH-ORIGIN",
    world="NeeDoh / dumpling squishy hunt (LH Card 2)",
    gravity="YES",
    q="How do I obtain authentic NeeDoh/squishy when stores limit stock and counterfeits abound?",
    q_indep="YES",
    answers="Restock trackers (r/NeeDoh, Squish Stock); retailer per-person limits; CPSC/recall/authenticity coverage. Promo cannot mint stock.",
    owner="RESTOCK/DROP NETWORKS; INVENTORY NETWORKS; OTHER (regulator/safety)",
    occ="OWNED",
    rel="COMPETING",
    evidence="LH Card 2; Run6 NT4; VS VS-2.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis; occupation + LH together: heat without residual commercial space",
    naive_fn="NO",
    prov=OD,
    note="anti-gaming: restock discussion = owner of THIS question, not automatic ownership of every adjacent question",
)
add(
    run=6, id="R6-NT5", types="NT",
    world="KPDH licensed costume (Run6 echo)",
    gravity="YES",
    q="How do I obtain licensed KPDH costume (group/kid) under stockout?",
    q_indep="YES",
    answers="Spirit inventory / licensed retail; same owner family as R5-NT4.",
    owner="INVENTORY NETWORKS; RESTOCK/DROP NETWORKS",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run6 NT5; VS VS-1.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
)
add(
    run=6, id="R6-NT6/INT-5", types="NT|INT",
    world="Costco Monster Mash smash chocolate buy-or-bye",
    gravity="YES",
    q="How do I get Monster Mash at a better price / decide whether the smash novelty is worth it?",
    q_indep="YES",
    answers="Costco Instant Savings (~$39.99 tracker; some warehouses ~$19.97); deal-tracker culture.",
    owner="RETAILER SALES; CLEARANCE/MARKDOWNS; AFFILIATE DEAL CONTENT",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run6 NT6; INT-5 organic-only; VS VS-2; anti-gaming downgraded VS-3→VS-2 because surprising info IS the existing promo.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
    note="Price discussion present AND ownership real — Instant Savings answers the save question",
)
add(
    run=6, id="R6-NT7", types="NT",
    world="Snoopy cup / Pokémon TCG / Switch 2 Zelda (grouped limited drops)",
    gravity="YES",
    q="How do I obtain limited drop objects at MSRP instead of scalper price?",
    q_indep="YES",
    answers="Retail limits; restock trackers; scalper markets as the alternative path.",
    owner="RESTOCK/DROP NETWORKS; SCALPER/RESALE; INVENTORY NETWORKS",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run6 NT7; VS VS-2.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
)
add(
    run=6, id="R6-NT8", types="NT",
    world="Delivery make-right credit / don't pay twice",
    gravity="YES",
    q="How do I get compensated / avoid paying twice after delivery double-failure?",
    q_indep="YES",
    answers="Platform support credit / refund policy already the mechanism.",
    owner="PLATFORM REFUNDS/CREDITS",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run6 NT8; SCF-003; VS VS-1; salience-reject shape.",
    stage="SCOUT OUTPUT",
    helped="YES",
    how="prevented wasted synthesis",
    naive_fn="NO",
    prov=OD,
)
add(
    run=6, id="R6-NT9", types="NT",
    world="Store-credit panic / apology gift card / BNPL eased",
    gravity="YES",
    q="How do I escape expiring store-credit + BNPL trap, or enlarge apology gift-card relief?",
    q_indep="YES",
    answers="Retailer refund policy + BNPL terms own the trap mechanics; consumer-warning content explains it. Campaign cannot own a policy trap.",
    owner="STORE POLICY; BNPL TERMS",
    occ="OWNED",
    rel="COMPETING",
    evidence="Run6 NT9; VS VS-2; anti-gaming downgraded VS-3→VS-2.",
    stage="DURING SYNTHESIS",
    helped="YES",
    how="prevented wasted synthesis (policy-owned; information works against promo framing)",
    naive_fn="NO",
    prov=OD,
    note="Question exists; answered by policy — OWNED not UNOWNED",
)
add(
    run=6, id="R6-LH3", types="LH-ORIGIN",
    world="Food-illusion combos (weird pairings that taste like other foods; LH Card 3)",
    gravity="YES",
    q="NONE",
    q_indep="NO",
    answers="N/A — pure METHOD heat; no product/SKU center of gravity; commercial adjacency not observed.",
    owner="N/A",
    occ="UNCLEAR",
    rel="IRRELEVANT",
    evidence="LH Card 3; INT organic note; commercial E NONE.",
    stage="SCOUT OUTPUT",
    helped="NO",
    how="added no information (no natural economic question — not whitespace); LH found cultural gravity without commercial question",
    naive_fn="NO",
    prov=OD,
    note="FP guard: culturally strong + no deal found ≠ UNOWNED whitespace. OCCUPATION UNCLEAR with note no natural economic question — not whitespace.",
)

assert len(C) > 0
print(f"corpus_n={len(C)}")
